### ISSUE TITLE
Tests for the home page

### ISSUE THREAD

**Issue by amritsiidhu** [NewAcropolis/frontend#35]
Im trying to test that a certain article is being displayed, but due to this `randint`(I think) the article is always changing, so the test I created only passes on a few occasions. What steps should I take to get this passing?
See branch `tests-for-homeage`, line 16 `app/main/views/index.py` and the new tests created in `tests/app/mian/views/test_index.py`

**Comment by kentsanggds** [comment]
The aim of the articles at some stage is to allow a user to set the articles to be shown on the home screen, otherwise a random article will be shown as it might not always be set.

In order to test the random article you might want to mock the `randint` function with a random number set in the test and set up a number of articles to show that different articles are shown dependant on the int generated.

**Comment by AmritSidhu** [comment]
So ive decided to just test that the content on the page and the functionality of getting the `main_article` returns a string (not any specific string). It works when testing that it has got a string from the list of articles but when testing the page content its returning false:`where False = isinstance(u'Article title 1', str)`.  Although the content is being converted into a string. See line 53 in `tests/app/mian/views/test_index.py`

**Comment by amritsiidhu** [comment]
So ive decided to just test that the content on the page and the functionality of getting the `main_article` returns a string (not any specific string). It works when testing that it has got a string from the list of articles but when testing the page content its returning false:`where False = isinstance(u'Article title 1', str)`. Although the content is being converted into a string. See line 53 in `tests/app/mian/views/test_index.py`

**Comment by amritsiidhu** [comment]
Have found that when doing to conversion it become unicode which isinstance("unciode_string", str) the str doesn't cover unicode but using basestring does.
